[project]
name = "aurora"
version = "0.1.0"
description = "Aurora Solar Scheduler"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.5",
    "setuptools>=80.9.0",
]
